### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CREEATION** [GlowSand/bits-of-bark#1]
![image](https://user-images.githubusercontent.com/3277769/138498570-2b6ff88f-7fb4-4ee6-ba85-e9196b3ce820.png)

**Comment by SalvieMundi** [comment]
I'm probably not going to go through a big song and dance over this to make a pull request, but if you open the .jar with something like 7-Zip, and edit the fabric.mod.json file, you can just insert a single "}" without the quotes at the end of the file, and it should resolve the problem.

**Comment by SalvieMundi** [comment]
Actually, maybe I will do a pull request, because this mod has tons of problems.

**Comment by SalvieMundi** [comment]
Here's the mod as I compiled it. It will work on 1.17+ servers without crashing.
https://github.com/SalvieMundi/bits-of-bark/releases/tag/release

Also, here is the contents of my wood-barks.json configuration file. I would take out anything you aren't using, but wanted to provide it as it can be extremely tedious making the mod work with better end in particular. I also have traverse, apple trees revived and blockus stuff in there.

> {
>   "Hunger": 2,
>   "Saturation": 0.1,
>   "IsFuel": true,
>   "FuelTicks": 75,
>   "WoodTypes": {
>     "minecraft:stripped_warped_hyphae": "minecraft:warped_hyphae",
>     "minecraft:stripped_oak_wood": "minecraft:oak_wood",
>     "promenade:stripped_palm_log": "promenade:palm_log",
>     "promenade:stripped_dark_amaranth_stem": "promenade:dark_amaranth_stem",
>     "minecraft:stripped_dark_oak_log": "minecraft:dark_oak_log",
>     "promenade:stripped_palm_wood": "promenade:palm_wood",
>     "promenade:stripped_dark_amaranth_hyphae": "promenade:dark_amaranth_hyphae",
>     "minecraft:stripped_crimson_hyphae": "minecraft:crimson_hyphae",
>     "minecraft:stripped_birch_log": "minecraft:birch_log",
>     "minecraft:stripped_jungle_log": "minecraft:jungle_log",
>     "minecraft:stripped_crimson_stem": "minecraft:crimson_stem",
>     "minecraft:stripped_birch_wood": "minecraft:birch_wood",
>     "croptopia:stripped_cinnamon_wood": "croptopia:cinnamon_wood",
>     "woods_and_mires:stripped_pine_wood": "woods_and_mires:pine_wood",
>     "minecraft:stripped_oak_log": "minecraft:oak_log",
>     "croptopia:stripped_cinnamon_log": "croptopia:cinnamon_log",
>     "promenade:stripped_cherry_oak_wood": "promenade:cherry_oak_wood",
>     "minecraft:stripped_spruce_wood": "minecraft:spruce_wood",
>     "woods_and_mires:stripped_pine_log": "woods_and_mires:pine_log",
>     "minecraft:stripped_jungle_wood": "minecraft:jungle_wood",
>     "minecraft:stripped_acacia_log": "minecraft:acacia_log",
>     "minecraft:stripped_spruce_log": "minecraft:spruce_log",
>     "minecraft:stripped_dark_oak_wood": "minecraft:dark_oak_wood",
>     "promenade:stripped_cherry_oak_log": "promenade:cherry_oak_log",
>     "minecraft:stripped_warped_stem": "minecraft:warped_stem",
>     "minecraft:stripped_acacia_wood": "minecraft:acacia_wood",
>     "traverse:stripped_fir_log": "traverse:fir_log",
>     "traverse:stripped_fir_wood": "traverse:fir_wood",
>     "appletreesrev:stripped_apple_log": "appletreesrev:apple_log",
>     "appletreesrev:stripped_apple_wood": "appletreesrev:apple_wood",
>     "blockus:stripped_white_oak_log": "blockus:white_oak_log",
>     "blockus:stripped_white_oak_wood": "blockus:white_oak_wood",
> 	"betterend:dragon_tree_stripped_bark": "betterend:dragon_tree_bark",
> 	"betterend:dragon_tree_stripped_log": "betterend:dragon_tree_log",
> 	"betterend:end_lotus_stripped_bark": "betterend:end_lotus_bark",
> 	"betterend:end_lotus_stripped_log": "betterend:end_lotus_log",
> 	"betterend:hexlix_tree_stripped_bark": "betterend:helix_tree_bark",
> 	"betterend:helix_tree_stripped_log": "betterend:helix_tree_log",
> 	"betterend:jellyshroom_stripped_bark": "betterend:jellyshroom_bark",
> 	"betterend:jellyshroom_stripped_log": "betterend:jellyshroom_log",
> 	"betterend:lacugrove_stripped_bark": "betterend:lacugrove_bark",
> 	"betterend:lacugrove_stripped_log": "betterend:lacugrove_log",
> 	"betterend:lucernia_stripped_bark": "betterend:lucernia_bark",
> 	"betterend:lucernia_stripped_log": "betterend:lucernia_log",
> 	"betterend:mossy_glowshroom_stripped_bark": "betterend:mossy_glowshroom_bark",
> 	"betterend:mossy_glowshroom_stripped_log": "betterend:mossy_glowshroom_log",
> 	"betterend:pythadendron_stripped_bark": "betterend:pythadendron_bark",
> 	"betterend:pythadendron_stripped_log": "betterend:pythadendron_log",
> 	"betterend:tenanea_stripped_bark": "betterend:tenanea_bark",
> 	"betterend:tenanea_stripped_log": "betterend:tenanea_log",
> 	"betterend:umbrella_tree_stripped_bark": "betterend:umbrella_tree_bark",
> 	"betterend:umbrella_tree_stripped_log": "betterend:umbrella_tree_log"
>   },
>   "GiveBark": [
>     "#bitsofbark:give_bark",
>     "#moretags:dressed_wood",
>     "minecraft:birch_log",
>     "promenade:dark_amaranth_hyphae",
>     "minecraft:birch_wood",
>     "minecraft:spruce_log",
>     "promenade:dark_amaranth_stem",
>     "minecraft:warped_hyphae",
>     "minecraft:warped_stem",
>     "minecraft:crimson_stem",
>     "woods_and_mires:pine_wood",
>     "minecraft:crimson_hyphae",
>     "minecraft:jungle_log",
>     "minecraft:oak_log",
>     "minecraft:acacia_log",
>     "minecraft:jungle_wood",
>     "minecraft:oak_wood",
>     "promenade:cherry_oak_wood",
>     "woods_and_mires:pine_log",
>     "promenade:cherry_oak_log",
>     "minecraft:dark_oak_log",
>     "minecraft:dark_oak_wood",
>     "minecraft:acacia_wood",
>     "minecraft:spruce_wood",
>     "promenade:palm_wood",
>     "promenade:palm_log",
>     "croptopia:cinnamon_log",
>     "croptopia:cinnamon_wood",
>     "traverse:fir_log",
>     "traverse:fir_wood",
>     "appletreesrev:apple_log",
>     "appletreesrev:apple_wood",
>     "blockus:white_oak_log",
>     "blockus:white_oak_wood",
> 	"betterend:dragon_tree_bark",
> 	"betterend:dragon_tree_log",
> 	"betterend:end_lotus_bark",
> 	"betterend:end_lotus_log",
> 	"betterend:helix_tree_bark",
> 	"betterend:helix_tree_log",
> 	"betterend:jellyshroom_bark",
> 	"betterend:jellyshroom_log",
> 	"betterend:lacugrove_bark",
> 	"betterend:lacugrove_log",
> 	"betterend:lucernia_bark",
> 	"betterend:lucernia_log",
> 	"betterend:mossy_glowshroom_bark",
> 	"betterend:mossy_glowshroom_log",
> 	"betterend:pythadendron_bark",
> 	"betterend:pythadendron_log",
> 	"betterend:tenanea_bark",
> 	"betterend:tenanea_log",
> 	"betterend:umbrella_tree_bark",
> 	"betterend:umbrella_tree_log"
>   ],
>   "IsFood": false
> }
